// packages/svelte/src/index.svelte
<script lang="ts">
  import { onMount } from "svelte"
  import { createQrCode, type InlineConfig } from "qrcode-tiny"
  import { afterUpdate } from "svelte"

  type $$Props = InlineConfig

  let src: string

  onMount(() => {
    updateQrCodeSrc()
  });

  afterUpdate(() => {
    updateQrCodeSrc()
  });

  async function updateQrCodeSrc() {
    const { text, ecc, ...option } = $$props
    src = await createQrCode(text, ecc, option)
  }
</script>

<img {src} alt="Scan me" />

// packages/react/src/index.ts
import type { InlineConfig } from 'qrcode-tiny'
import { createQrCode } from 'qrcode-tiny'
import { createElement, type FC, useEffect, useState } from 'react'

const QrCode: FC<InlineConfig> = ({ text, ecc, ...option }) => {
  const [src, setSrc] = useState<string>()

  useEffect(() => {
    createQrCode(text, ecc, option).then(setSrc)
  }, [text, ecc, option])

  return createElement('img', { src })
}

export default QrCode
